version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - internal-network
#            - connection-to-kafka
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:54321/postgres
            SPRING_DATASOURCE_USERNAME: ${WISHER_DB_USER}
            SPRING_DATASOURCE_PASSWORD: ${WISHER_DB_PASSWORD}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            S3_ID: ${S3_ID}
            S3_KEY: ${S3_KEY}
            SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: wisher
            POSTGRES_USER: ${WISHER_DB_USER}
            POSTGRES_PASSWORD: ${WISHER_DB_PASSWORD}
        ports:
            - "54321:54321"
        networks:
            - internal-network
        expose:
            - "54321"
        command:
            - -p 54321
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:

networks:
    internal-network:
        driver: bridge
#    connection-to-kafka:
#        name: connet
#        external: true
