spring:
  application:
    name: api
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml


security:
    jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration-time: 7

logging:
    level:
        org:
            springframework:
                security=DEBUG:
