name: Deploy to Remote Machine

on:
    push:
        branches:
            - main
            - ci-cd-pipeline

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up SSH
                uses: webfactory/ssh-agent@v0.5.3
                with:
                    ssh-private-key: ${{ secrets.SSH_VDSINA_PRIVATE_KEY }}

            -   name: Add remote server to known_hosts
                run: |
                    ssh-keyscan -H ${{ secrets.VDSINA_MACHINE_ADDRESS }} >> ~/.ssh/known_hosts        

            -   name: Pull latest changes from main
                run: |
                    ssh ${{ secrets.VDSINA_MACHINE_USER }}@${{ secrets.VDSINA_MACHINE_ADDRESS }} 'cd /home/wisher-backend && git pull origin main'

            -   name: Deploy using Docker Compose
                run: |
                    ssh ${{ secrets.VDSINA_MACHINE_USER }}@${{ secrets.VDSINA_MACHINE_ADDRESS }} 'cd /home/wisher-backend && docker-compose down && docker-compose up -d'
