name: Deploy to Remote Machine

on:
    push:
        branches:
            - fix-cors-and-security

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Cache Gradle dependencies
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Set up SSH
                uses: webfactory/ssh-agent@v0.5.3
                with:
                    ssh-private-key: ${{ secrets.SSH_VDSINA_PRIVATE_KEY }}

            -   name: Add remote server to known_hosts
                run: |
                    ssh-keyscan -H ${{ secrets.VDSINA_MACHINE_ADDRESS }} >> ~/.ssh/known_hosts        

            -   name: Pull latest changes from fix-cors-and-security
                run: |
                    ssh ${{ secrets.VDSINA_MACHINE_USER }}@${{ secrets.VDSINA_MACHINE_ADDRESS }} 'cd /home/wisher-backend && git checkout fix-cors-and-security && git pull origin fix-cors-and-security'

            -   name: Build Docker images
                run: |
                    ssh ${{ secrets.VDSINA_MACHINE_USER }}@${{ secrets.VDSINA_MACHINE_ADDRESS }} 'cd /home/wisher-backend && docker-compose build --rm --no-cache'

            -   name: Deploy using Docker Compose
                run: |
                    ssh ${{ secrets.VDSINA_MACHINE_USER }}@${{ secrets.VDSINA_MACHINE_ADDRESS }} 'cd /home/wisher-backend && docker-compose up -d'

            -   name: Remove temporary containers
                run: |
                    ssh ${{ secrets.VDSINA_MACHINE_USER }}@${{ secrets.VDSINA_MACHINE_ADDRESS }} 'docker container prune -f'
