name: CI/CD Pipeline

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    test:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:19.03.12
                options: --privileged
                ports:
                    - 5432:5432
                volumes:
                    - /var/run/docker.sock:/var/run/docker.sock

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Compose
              run: docker-compose -f docker-compose.yml up -d

            - name: Run Unit Tests
              run: ./gradlew test

            - name: Tear down Docker Compose
              run: docker-compose -f docker-compose.yml down

#    deploy:
#        name: Deploy to Render.com
#        runs-on: ubuntu-latest
#        needs: test
#        if: github.event_name == 'workflow_dispatch'
#
#        steps:
#            - name: Checkout code
#              uses: actions/checkout@v3
#
#            - name: Deploy to Render.com
#              env:
#                  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
#              run: |
#                  curl -X POST \
#                  -H "Authorization: Bearer $RENDER_API_KEY" \
#                  -H "Content-Type: application/json" \
#                  -d '{"serviceId": "your-service-id"}' \
#                  https://api.render.com/v1/services/your-service-id/deploys
